// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMmtSURXTukrjaHgbS_WFroOTxAVRVVMk',
    appId: '1:592535631126:web:dbbd627745e5dfd5524c37',
    messagingSenderId: '592535631126',
    projectId: 'testing-cli-776f9',
    authDomain: 'testing-cli-776f9.firebaseapp.com',
    storageBucket: 'testing-cli-776f9.appspot.com',
    measurementId: 'G-Q53H4CEQHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk0xTGpAGq8ImOJAGyxGbUJ-GLcm0qgAA',
    appId: '1:592535631126:android:9441d1a74de70b29524c37',
    messagingSenderId: '592535631126',
    projectId: 'testing-cli-776f9',
    storageBucket: 'testing-cli-776f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRx3pRnnONY6g73Kx6h2dXC_XqYovHnQc',
    appId: '1:592535631126:ios:e5108e61fd9d5fa1524c37',
    messagingSenderId: '592535631126',
    projectId: 'testing-cli-776f9',
    storageBucket: 'testing-cli-776f9.appspot.com',
    iosBundleId: 'com.example.cliExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRx3pRnnONY6g73Kx6h2dXC_XqYovHnQc',
    appId: '1:592535631126:ios:e5108e61fd9d5fa1524c37',
    messagingSenderId: '592535631126',
    projectId: 'testing-cli-776f9',
    storageBucket: 'testing-cli-776f9.appspot.com',
    iosBundleId: 'com.example.cliExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMmtSURXTukrjaHgbS_WFroOTxAVRVVMk',
    appId: '1:592535631126:web:14e8f6332ac8723a524c37',
    messagingSenderId: '592535631126',
    projectId: 'testing-cli-776f9',
    authDomain: 'testing-cli-776f9.firebaseapp.com',
    storageBucket: 'testing-cli-776f9.appspot.com',
    measurementId: 'G-02RN3W9QR5',
  );
}
